const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)');
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.section>h2,.section>.eyebrow,.two-col,.wide-copy,.repository,.feature-grid article,.results>div,.evolution-grid article,.workflow,.case-display').forEach(el=>{el.classList.add('reveal');observer.observe(el)});
const dialog=document.getElementById('detailDialog');const content=document.getElementById('dialogContent');let returnFocus;function openDialog(html,button){returnFocus=button;content.innerHTML=html;dialog.showModal()}dialog.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>returnFocus?.focus());dialog.addEventListener('click',e=>{if(e.target===dialog&&!(e.clientX>=dialog.getBoundingClientRect().left&&e.clientX<=dialog.getBoundingClientRect().right&&e.clientY>=dialog.getBoundingClientRect().top&&e.clientY<=dialog.getBoundingClientRect().bottom))dialog.close()});
document.getElementById('filmButton').onclick=function(){openDialog('<div class="eyebrow">THE KADAL VISION</div><h2>The end of editions. <br><span>The start of precision.</span></h2><p>Connect your content. Understand the impact of every change. Coordinate AI and editorial expertise. Deliver exactly what your market needs.</p><p>One content intelligence and orchestration platform, from continuous publishing to purpose-built products on demand.</p><p style="font-size:16px">Brand film coming soon.</p>',this)};
document.getElementById('storyButton').onclick=function(){openDialog('<div class="eyebrow">CLIENT STORY · K12 CONTENT PROVIDER</div><h2>Connected intelligence,<br><span>put to work.</span></h2><p>Kadal helped a K12 content provider modernize a large content estate and reduce the manual effort required to move content forward.</p><p><b>1,000+ lessons modernized</b><br><b>70,000+ assessment items generated</b><br><b>25 to 40% less manual effort</b></p><p>A connected foundation for faster, more coordinated publishing.</p>',this)};
const cases=[{title:'A custom edition. <br>For one university.',text:'A custom book and a full ancillary set for a single university, assembled from connected, governed content.',outputs:['Custom textbook','Assessment bank','Instructor resources']},{title:'A new market. <br>From approved content.',text:'A new market or localization variant of an existing title, without starting a new production cycle from scratch.',outputs:['Localized title','Market-specific assessments','Aligned ancillary set']},{title:'Built around<br>the people who publish.',text:'A purpose-built interface for a specific author, editor, or learning designer, with the context and workflows they need.',outputs:['Author workspace','Editorial review','Learning design tools']}];
document.querySelectorAll('[data-case]').forEach(button=>{button.setAttribute('aria-pressed',button.classList.contains('active'));button.onclick=()=>{const n=Number(button.dataset.case),c=cases[n];if(!reducedMotion.matches&&!document.documentElement.classList.contains('motion-paused')){document.querySelector('.precision-preview').animate([{opacity:.3,transform:'translateY(10px)'},{opacity:1,transform:'translateY(0)'}],{duration:450,easing:'ease-out'});}document.querySelectorAll('[data-case]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',b===button)});document.querySelector('.precision-preview').dataset.variant=String(n);document.getElementById('previewLabel').textContent=['Institution edition','Market localization','Role workspaces'][n];document.getElementById('previewSource').textContent=['Biology · Golden Repository','Approved title · Connected catalogue','Shared content · Publisher rules'][n];document.getElementById('caseNumber').textContent=`0${n+1} / PRECISION PUBLISHING`;document.getElementById('caseTitle').innerHTML=c.title;document.getElementById('caseText').textContent=c.text;document.getElementById('outputs').innerHTML=c.outputs.map(t=>`<div>${t}</div>`).join('')+'<small>ONE FOUNDATION. PURPOSE-BUILT OUTPUTS.</small>'}});
// Stagger related elements while respecting the visitor's motion preference.
document.querySelectorAll('.feature-grid,.results,.evolution-grid').forEach(group=>[...group.children].forEach((el,i)=>el.style.setProperty('--stagger',`${(i%3)*100}ms`)));
document.querySelectorAll('.control-panel>div').forEach((el,i)=>el.style.setProperty('--row-delay',`${i*120}ms`));
const motionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');motionObserver.unobserve(entry.target)}}),{threshold:.25});document.querySelectorAll('.map-area,.control-panel').forEach(el=>motionObserver.observe(el));
const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){document.querySelectorAll('nav a').forEach(a=>{if(a.hash==='#'+entry.target.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}}),{rootMargin:'-15% 0px -60% 0px'});document.querySelectorAll('#intelligence,#orchestration,#impact').forEach(el=>sectionObserver.observe(el));
const motionButton=document.getElementById('motionToggle');motionButton.addEventListener('click',()=>{const paused=document.documentElement.classList.toggle('motion-paused');motionButton.setAttribute('aria-pressed',String(paused));motionButton.textContent=paused?'Resume motion ▷':'Pause motion Ⅱ';});
document.querySelectorAll('.repo-card').forEach(card=>{card.querySelectorAll('.context-row,.impact-row,.lineage-track>div').forEach((row,i)=>row.style.setProperty('--row-delay',`${i*.25}s`));});
// Finite entrance animation; layered colour responds gently to the pointer.
const cardArrivalObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('card-arrived');cardArrivalObserver.unobserve(entry.target);}});},{threshold:.2});
document.querySelectorAll('.repo-card').forEach(card=>{cardArrivalObserver.observe(card);card.addEventListener('pointermove',event=>{if(event.pointerType==='touch'||reducedMotion.matches||document.documentElement.classList.contains('motion-paused'))return;const r=card.getBoundingClientRect();card.style.setProperty('--art-x',`${((event.clientX-r.left)/r.width-.5)*18}px`);card.style.setProperty('--art-y',`${((event.clientY-r.top)/r.height-.5)*14}px`);});card.addEventListener('pointerleave',()=>{card.style.setProperty('--art-x','0px');card.style.setProperty('--art-y','0px');});});
const speedSection=document.querySelector('.speed');
if(speedSection){speedSection.querySelectorAll('.pills span').forEach((pill,i)=>pill.style.setProperty('--product-delay',`${i*.1}s`));const speedObserver=new IntersectionObserver(entries=>{if(entries[0].isIntersecting){if(!reducedMotion.matches&&!document.documentElement.classList.contains('motion-paused'))speedSection.classList.add('speed-reveal');speedObserver.disconnect();}},{threshold:.3});speedObserver.observe(speedSection.querySelector('.speed-grid'));}
