(()=>{
const stage=document.querySelector('.precision-stage'),preview=stage.querySelector('.precision-preview'),outputs=document.getElementById('outputs'),detail=document.getElementById('outputDetail'),pause=document.getElementById('precisionPause'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
const descriptions=[['A focused textbook, assembled around the university’s learning goals.','Questions aligned to the selected concepts and course outcomes.','Teaching notes and activities connected to the custom edition.'],['Approved concepts adapted to regional language and context.','Questions reviewed against local standards and terminology.','Teaching resources kept aligned with the localized title.'],['Source content and revision context in one author workspace.','Changes, quality checks, and approvals in an editorial view.','Concepts and learning outcomes connected for course design.']];
let variant=0,selected=0,visible=false,userPaused=false,hovering=false,timer=null;
function choose(i){selected=i;outputs.querySelectorAll('button').forEach((b,j)=>b.setAttribute('aria-pressed',String(i===j)));detail.textContent=descriptions[variant][i];preview.dataset.output=String(i);}
function render(){document.getElementById('precisionRequest').textContent=['Create a biology edition for our university.','Adapt this title for a new market.','Give each publishing role the right workspace.'][variant];document.getElementById('precisionResponse').textContent=['Assemble a textbook, assessments, and teaching resources.','Adapt approved content to local requirements.','Give authors, editors, and designers the context they need.'][variant];const names=[...outputs.children].filter(e=>e.tagName!=='SMALL').map(e=>e.textContent.trim());outputs.replaceChildren();names.forEach((name,i)=>{const b=document.createElement('button');b.type='button';b.innerHTML='<span class="output-index">0'+(i+1)+'</span><span>'+name+'</span><span class="output-check" aria-hidden="true">✓</span>';b.addEventListener('click',()=>{choose(i);userPaused=true;sync();});outputs.append(b);});choose(0);sync();}
function sync(){clearTimeout(timer);const stopped=userPaused||reduced.matches||document.documentElement.classList.contains('motion-paused');pause.textContent=stopped?'Resume animation ▷':'Pause animation Ⅱ';pause.setAttribute('aria-pressed',String(stopped));stage.classList.toggle('is-running',visible&&!stopped&&!hovering);if(visible&&!stopped&&!hovering&&!document.hidden)timer=setTimeout(()=>{choose((selected+1)%3);sync();},2800);}
pause.addEventListener('click',()=>{if(document.documentElement.classList.contains('motion-paused')){document.documentElement.classList.remove('motion-paused');const all=document.getElementById('motionToggle');all.setAttribute('aria-pressed','false');all.textContent='Pause motion Ⅱ';userPaused=false;}else userPaused=!userPaused;sync();});
document.querySelectorAll('[data-case]').forEach(b=>b.addEventListener('click',()=>{variant=Number(b.dataset.case);stage.dataset.variant=String(variant);render();}));
stage.addEventListener('pointermove',e=>{if(reduced.matches||userPaused||document.documentElement.classList.contains('motion-paused'))return;const r=stage.getBoundingClientRect();stage.style.setProperty('--pointer-x',`${(e.clientX-r.left)/r.width*100}%`);stage.style.setProperty('--pointer-y',`${(e.clientY-r.top)/r.height*100}%`);});
outputs.addEventListener('pointerenter',()=>{hovering=true;sync();});outputs.addEventListener('pointerleave',()=>{hovering=false;sync();});outputs.addEventListener('focusin',()=>{hovering=true;sync();});outputs.addEventListener('focusout',()=>{hovering=false;sync();});
new IntersectionObserver(e=>{visible=e[0].isIntersecting;sync();},{threshold:.2}).observe(stage);new MutationObserver(sync).observe(document.documentElement,{attributes:true,attributeFilter:['class']});reduced.addEventListener('change',sync);document.addEventListener('visibilitychange',sync);render();
})();
