(()=>{
const story=document.getElementById('knowledgeStory'),sticky=story.querySelector('.knowledge-sticky'),planes=[...story.querySelectorAll('[data-plane]')],layerButtons=[...story.querySelectorAll('[data-layer]')];
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const layerCopy=[['THE FOUNDATION','Your content, brought together.','Manuscripts, assessment items, and media retain their rights, versions, and provenance in one connected system of record.','Example: a biology chapter, its diagrams, and its assessment items.'],['THE SHARED LANGUAGE','Define what your content means.','An educational ontology defines concepts, standards, and rules, giving every asset a shared structure and meaning.','Example: cell structure is a concept, linked to learning standards and editorial rules.'],['THE RELATIONSHIPS','Make the connections visible.','The knowledge map links concepts to learning goals, related assets, and dependent products so teams can trace the impact of a change.','Example: cell structure connects to organelles, cell function, and learning goals.'],['THE POSSIBILITIES','Carry intelligence into every output.','Titles, courses, and assessments draw from the same connected foundation, with context and lineage retained.','Example: one revised concept can be traced across the textbook, course, and question bank.']];
let layer=-1,scrollFrame=0,manual=false;
function setLayers(progress,selected){const complete=reduced.matches||getComputedStyle(sticky).position!=='sticky';const spread=complete?1:progress;planes.forEach((p,i)=>{p.style.transition=reduced.matches?'none':'transform .75s cubic-bezier(.2,.7,.2,1), opacity .8s';p.style.transform=`translateY(${410-i*(18+spread*97)}px)`;p.style.opacity=i<=selected?'1':'.3';p.classList.toggle('is-current',i===selected)});story.querySelector('.knowledge-progress span').style.width=`${25+progress*75}%`;if(layer===selected)return;layer=selected;layerButtons.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===selected)));const c=layerCopy[selected];document.getElementById('layerKicker').textContent=c[0];document.getElementById('layerTitle').textContent=c[1];document.getElementById('layerBody').textContent=c[2];document.getElementById('layerExample').textContent=c[3];}
function scrollUpdate(){scrollFrame=0;if(manual)return;const box=story.getBoundingClientRect(),height=sticky.getBoundingClientRect().height,offset=parseFloat(getComputedStyle(sticky).top)||0;const progress=Math.max(0,Math.min(1,(offset-box.top)/Math.max(1,box.height-height)));setLayers(progress,Math.min(3,Math.floor(progress*4)));}
layerButtons.forEach((b,i)=>b.addEventListener('click',()=>{manual=true;setLayers(i/3,i)}));
window.addEventListener('scroll',()=>{manual=false;if(!scrollFrame)scrollFrame=requestAnimationFrame(scrollUpdate)},{passive:true});window.addEventListener('resize',()=>{manual=false;scrollUpdate()});reduced.addEventListener('change',scrollUpdate);scrollUpdate();
const journey=document.getElementById('publishingJourney'),run=document.getElementById('runWorkflow'),stages=[...journey.querySelectorAll('[data-work-stage]')],states=[...journey.querySelectorAll('[data-task-state]')];
const copy=[['CONTENT INTELLIGENCE','Know what needs to change.','A source revision is connected to its concepts, related assets, and dependent products. The scope becomes visible before production begins.','Scope identified','Linked','Concept relationships mapped'],['AI + EDITORIAL EXPERTS','Move the right work forward.','AI agents and editorial experts coordinate updates across the affected content. Every task follows the workflow your team defines.','Updating content','In progress','Updates coordinated across linked products'],['HUMAN JUDGMENT','Keep approval in expert hands.','Quality rules guide the checks. Editors review the affected content and approve it before delivery.','Editorial review','For review','Human approval required before publishing'],['CONNECTED DELIVERY','Ready, together.','Approved content moves into aligned outputs, preserving the context and lineage of the source revision.','Ready to publish','Approved','Approved content ready for delivery']];
let current=0,playing=false,timer=null,userPaused=false,inView=false,stageAnimation=null;
function showStage(i,animate=true){current=i;journey.dataset.stage=String(i);stages.forEach((b,j)=>{b.setAttribute('aria-pressed',String(i===j));b.classList.toggle('is-complete',j<i)});journey.querySelector('.journey-rail span').style.width=`${(i+1)*25}%`;const c=copy[i];['journeyRole','journeyTitle','journeyText','ticketStatus'].forEach((id,j)=>document.getElementById(id).textContent=c[j]);states.forEach(s=>s.textContent=c[4]);document.getElementById('journeyGate').textContent=c[5];if(animate&&playing&&!reduced.matches&&!document.documentElement.classList.contains('motion-paused'))stageAnimation=document.getElementById('journeyLive').animate([{opacity:.5,transform:'translateY(7px)'},{opacity:1,transform:'translateY(0)'}],{duration:550,easing:'ease-out'});}
function stop(){playing=false;journey.dataset.playing='false';stageAnimation?.cancel();clearTimeout(timer);timer=null;run.textContent=reduced.matches?'Next stage':'Resume animation ▷';run.setAttribute('aria-pressed','true');}
function canPlay(){return inView&&!userPaused&&!reduced.matches&&!document.hidden&&!document.documentElement.classList.contains('motion-paused');}
function next(){if(!canPlay()){stop();return;}showStage((current+1)%4);document.getElementById('workflowStatus').textContent=`Step ${current+1} of 4: ${['Understand','Coordinate','Approve','Publish'][current]}`;timer=setTimeout(next,current===3?4500:3400);}
function start(){if(!canPlay()||playing)return;playing=true;journey.dataset.playing='true';run.textContent='Pause animation Ⅱ';run.setAttribute('aria-pressed','false');timer=setTimeout(next,3400);}
run.addEventListener('click',()=>{if(reduced.matches){showStage((current+1)%4,false);return;}if(playing){userPaused=true;stop();document.getElementById('workflowStatus').textContent='Paused. Select a stage or resume the workflow.';}else{userPaused=false;if(document.documentElement.classList.contains('motion-paused')){document.documentElement.classList.remove('motion-paused');const all=document.getElementById('motionToggle');all.setAttribute('aria-pressed','false');all.textContent='Pause motion Ⅱ';}start();}});
stages.forEach((b,i)=>b.addEventListener('click',()=>{userPaused=true;stop();showStage(i);document.getElementById('workflowStatus').textContent=`Step ${i+1} of 4: ${['Understand','Coordinate','Approve','Publish'][i]}`}));
journey.querySelectorAll('.journey-tasks>div').forEach((el,i)=>el.style.setProperty('--task-delay',`${i*.3}s`));
new IntersectionObserver(entries=>{inView=entries[0].isIntersecting;if(inView)start();else stop();},{threshold:.15}).observe(journey);
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();else start();});
new MutationObserver(()=>{if(document.documentElement.classList.contains('motion-paused'))stop();else start();}).observe(document.documentElement,{attributes:true,attributeFilter:['class']});
reduced.addEventListener('change',()=>{if(reduced.matches){stop();run.textContent='Next stage';}else start();});showStage(0,false);if(reduced.matches)run.textContent='Next stage';
// A single pinned scroll narrative; dragging updates the same scroll position.
const viewport=document.querySelector('.cards-scroll-window'),track=viewport.querySelector('.repository-cards'),cards=[...track.children],cardStory=document.querySelector('.cards-scroll-story'),cardSticky=document.querySelector('.cards-scroll-sticky');
let travel=0,target=0,currentX=0,frame=0,pinned=false,drag=null;
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
function drawCards(){frame=0;currentX+= (target-currentX)*.18;if(Math.abs(target-currentX)<.2)currentX=target;track.style.transform=`translate3d(${-currentX}px,0,0)`;if(currentX!==target)frame=requestAnimationFrame(drawCards);}
function syncCards(){if(!pinned)return;const top=parseFloat(getComputedStyle(cardSticky).top)||0;target=clamp(top-cardStory.getBoundingClientRect().top,0,travel);if(reduced.matches||document.documentElement.classList.contains('motion-paused'))currentX=target;if(!frame)frame=requestAnimationFrame(drawCards);}
function fitCarousel(){document.documentElement.style.setProperty('--page-width',document.documentElement.clientWidth+'px');travel=Math.max(0,track.scrollWidth-viewport.clientWidth);pinned=!reduced.matches&&innerHeight>cardSticky.offsetHeight+125;cardStory.classList.toggle('is-pinned',pinned);cardStory.style.setProperty('height',pinned?`${cardSticky.offsetHeight+travel}px`:'auto','important');if(!pinned){cancelAnimationFrame(frame);frame=0;track.style.transform='none';}else{viewport.scrollLeft=0;syncCards();}}
function moveTo(x){x=clamp(x,0,travel);if(pinned){const top=parseFloat(getComputedStyle(cardSticky).top)||0;window.scrollTo({top:window.scrollY+cardStory.getBoundingClientRect().top-top+x,behavior:'instant'});}else viewport.scrollLeft=x;}
viewport.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,origin:pinned?target:viewport.scrollLeft,active:false};});
viewport.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(!drag.active&&Math.abs(dx)>6&&Math.abs(dx)>Math.abs(dy)){drag.active=true;viewport.setPointerCapture(e.pointerId);viewport.classList.add('is-dragging');}if(drag.active){e.preventDefault();moveTo(drag.origin-dx);}});
function release(){drag=null;viewport.classList.remove('is-dragging');}viewport.addEventListener('pointerup',release);viewport.addEventListener('pointercancel',release);viewport.addEventListener('lostpointercapture',release);
viewport.addEventListener('wheel',e=>{if(pinned&&Math.abs(e.deltaX)>Math.abs(e.deltaY)){e.preventDefault();moveTo(target+e.deltaX);}},{passive:false});
viewport.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();moveTo((pinned?target:viewport.scrollLeft)+(e.key==='ArrowRight'?1:-1)*(cards[0].offsetWidth+24));}});
window.addEventListener('scroll',syncCards,{passive:true});window.addEventListener('resize',fitCarousel);reduced.addEventListener('change',fitCarousel);new ResizeObserver(fitCarousel).observe(cardSticky);fitCarousel();
const cardObserver=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('card-in-view',e.isIntersecting)),{threshold:.25});cards.forEach(c=>cardObserver.observe(c));
const preview=document.querySelector('.precision-preview');new IntersectionObserver(entries=>preview.classList.toggle('is-on-screen',entries[0].isIntersecting),{threshold:.15}).observe(preview);
})();
